
package:
  name: moenchzmq
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  - path: ../..

build:
  number: 0
  binary_relocation: True
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake
    - libstdcxx-ng
    - libgcc-ng
    - zeromq
    - libtiff
    - slsdetlib {{ environ.get('GIT_DESCRIBE_TAG', '') }}

  host:
    - zeromq
    - libtiff
    - slsdetlib {{ environ.get('GIT_DESCRIBE_TAG', '') }}

  run: 
    - libstdcxx-ng
    - libgcc-ng
    - zeromq
    - libtiff
    - slsdetlib {{ environ.get('GIT_DESCRIBE_TAG', '') }}
